// <auto-generated />
using System;
using AppTest.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AppTest.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210119132217_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("AppTest.Db.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Redactor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("AppTest.Db.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@admin.ru",
                            Login = "admin",
                            Name = "Name",
                            PasswordHash = new byte[] { 148, 24, 237, 69, 73, 90, 155, 15, 222, 84, 15, 2, 30, 6, 254, 14, 227, 158, 183, 167, 16, 218, 30, 247, 165, 88, 0, 227, 194, 172, 65, 10, 253, 241, 91, 18, 239, 114, 140, 88, 213, 132, 33, 1, 249, 18, 1, 83, 34, 86, 55, 148, 53, 173, 13, 227, 29, 105, 166, 11, 12, 6, 224, 241 },
                            PasswordSalt = new byte[] { 222, 30, 170, 27, 58, 113, 187, 59, 98, 246, 178, 55, 77, 129, 106, 154, 200, 12, 240, 139, 116, 109, 93, 34, 51, 232, 28, 42, 203, 50, 201, 236, 36, 162, 227, 189, 108, 234, 230, 163, 48, 147, 76, 26, 41, 157, 127, 169, 172, 13, 178, 86, 228, 194, 231, 227, 74, 154, 60, 183, 164, 104, 15, 77, 220, 51, 27, 253, 52, 56, 134, 67, 157, 87, 108, 215, 158, 167, 72, 186, 171, 33, 200, 58, 27, 70, 213, 160, 126, 0, 196, 240, 90, 222, 82, 70, 178, 29, 169, 109, 106, 87, 247, 91, 70, 80, 136, 52, 43, 33, 33, 202, 160, 193, 65, 9, 243, 205, 45, 216, 117, 54, 39, 83, 239, 98, 64, 67 }
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("AppTest.Db.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppTest.Db.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
